---

- name: install dependencies  # sudo apt install nodejs npm
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2  # sudo npm install pm2 -g
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
    state: present

- name: Extract artifact to EC2
  become: yes
  unarchive: 
    src: files/artifact.tar.gz
    dest: /home/ubuntu

- name: Start the app
  become: yes
  shell: |
    cd /home/ubuntu
    npm install
    npm install -g ts-node
    pm2 stop default
    pm2 start npm -- start
    # pm2 delete all
    # pm2 start npm -- start  