---

- name: install dependencies  # sudo apt install nodejs npm
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2  # sudo npm install pm2 -g
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: extract artifact
  become: yes
  unarchive: 
    src: files/artifact.tar.gz
    dest: .

- name: Start the app
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start  